########################################
#  KITTY CONFIG — "Kali Void" theme
#  ~/.config/kitty/kitty.conf
########################################

# ---------- FONT ----------
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11
disable_ligatures never
adjust_line_height  110%

# ---------- CURSOR ----------
cursor_shape         block
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# ─────────────────────────────────────────────
# Cursor trail
# ─────────────────────────────────────────────

#cursor_trail 1
#custom_shaders cursor-trail-motion-blur


# ─────────────────────────────────────────────
# Animated background
# ─────────────────────────────────────────────

#custom_shaders northern-lights

# ---------- OPACITY (static) ----------
background_opacity 0.65
background_blur    32

# ---------- WINDOW ----------
window_padding_width   3
hide_window_decorations titlebar-only
confirm_os_window_close 0

# ---------- TAB BAR ----------
#tab_bar_edge            top
#tab_bar_style           powerline
#tab_powerline_style     slanted
#tab_bar_min_tabs        1
#tab_title_template      " {index}: {title} "
#active_tab_font_style   bold-italic
#inactive_tab_font_style normal

# ---------- MISC ----------
scrollback_lines       10000
enable_audio_bell      no
remember_window_size   yes
shell                  zsh
term                   xterm-256color

# ---------- COLOR SCHEME — "Kali Void" ----------
# Based on Kali/OffSec's real brand palette:
# Valhalla navy-purple, Virtue Violet, Shift Blue, Giving Yellow

foreground            #d6d2e8
background            #241b35
selection_foreground  #120c1f
selection_background  #9a30d4

cursor            #9a30d4
cursor_text_color #120c1f

url_color #136ef6

# tab bar colors
active_tab_foreground   #120c1f
active_tab_background   #9a30d4
inactive_tab_foreground #5e537b
inactive_tab_background #1c1430
tab_bar_background      #0a0714

# window border colors
active_border_color   #9a30d4
inactive_border_color #281b4f
bell_border_color     #fd0133

# black
color0  #120c1f
color8  #5e537b

# red
color1  #fd0133
color9  #ff5c7c

# green
color2  #10b210
color10 #5fe15f

# yellow
color3  #fcd329
color11 #ffe98a

# blue
color4  #136ef6
color12 #6fa6ff

# magenta / violet
color5  #9a30d4
color13 #c17dff

# cyan / teal
color6  #ceeae6
color14 #eafffb

# white
color7  #d6d2e8
color15 #ffffff
